splash = false
ipc = true
wallpaper {
	monitor = eDP-1
	path = ~/Downloads/people_walking_on_a_platform.jpg
	fit_mode = cover
}
wallpaper {
	monitor = DP-1
	path = ~/Downloads/algeria_vibes.jpg
	fit_mode = cover
}
