splash = false
ipc = true
wallpaper {
	monitor = eDP-1
	path = ~/pictures/people_walking_on_a_platform.jpg
	fit_mode = cover
}
wallpaper {
	monitor = DP-1
	path = ~/pictures/rocky_desert.jpg
	fit_mode = cover
}
